#:import app_style util.style.app_style
<AssessmentManager>:
    canvas:
        Color:
            rgba: app_style['assessment_background']
    FloatLayout:
        id: assessment_grid
        Button:
            size: 300, 200
            text: "Start"
            background_normal: 'assets/next-arrow.png'
            id: submit
            on_release:
                root.advance_question()








