<Module>:
    
    FloatLayout:
        
        Button:
            text: 'ASSESSMENT'
            on_press: root.load_assessment()
            pos_hint: {"x": .3, "y": .35}
            size_hint: (.4, .075)

        MDLabel:
            pos_hint: {"x": .3, "top": .9}
            size_hint: (.4, .1)
            text: "Settings "
            halign: "center"
            theme_text_color: "Primary"
            id: dialogue_label

	            
