<Module>:
    
    FloatLayout:
        id: float

        MDIconButton:
            icon: 'assets/next-arrow.png'
            pos_hint: {'x': 0.85, 'top': 0.6}
            user_font_size: '64sp'
            on_press: root.advance_line()

        MDIconButton:
            icon: 'assets/prev-arrow.png'
            pos_hint: {'x': -0.05, 'top': 0.6}
            user_font_size: '64sp'
            on_press: root.previous_line()

	            
